name: Playwright Tests + Allure + Slack

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # ===============================
      # 🚀 Slack Start Notification
      # ===============================
      - name: Slack Start Notification
        run: |
          IST_TIME=$(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')

          curl -X POST \
          -H "Content-Type: application/json" \
          --data "{
            \"text\":\"🚀 *Playwright Automation Started*\n\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref_name }}\nTriggered By: ${{ github.actor }}\nTime: ${IST_TIME}\"
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      # ===============================
      # Checkout
      # ===============================
      - uses: actions/checkout@v4

      # ===============================
      # Node
      # ===============================
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # ===============================
      # Install Dependencies
      # ===============================
      - name: Install Dependencies
        run: npm ci

      # ===============================
      # Install Playwright
      # ===============================
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # ===============================
      # Run Tests
      # ===============================
      - name: Run Playwright Tests
        run: |
          npx playwright test --project=chromium

      # ===============================
      # Upload Videos
      # ===============================
      - name: Upload Failed Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failed-videos
          path: test-results/**/*.webm

      # ===============================
      # Upload Traces
      # ===============================
      - name: Upload Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: test-results/**/*.zip

      # ===============================
      # Upload Screenshots
      # ===============================
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: test-results/**/*.png

      # ===============================
      # Upload results.json
      # ===============================
      - name: Upload results.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-json
          path: results.json

      # ===============================
      # Parse Final Results
      # ===============================
      - name: Parse Test Results
        id: results
        if: always()
        run: |

          sudo apt-get update

          sudo apt-get install -y jq

          PASSED=$(jq '.stats.expected' results.json)

          FAILED=$(jq '.stats.unexpected' results.json)

          FLAKY=$(jq '.stats.flaky' results.json)

          TOTAL=$((PASSED+FAILED+FLAKY))

          echo "passed=$PASSED" >> $GITHUB_OUTPUT

          echo "failed=$FAILED" >> $GITHUB_OUTPUT

          echo "flaky=$FLAKY" >> $GITHUB_OUTPUT

          echo "total=$TOTAL" >> $GITHUB_OUTPUT

          echo "Passed : $PASSED"

          echo "Failed : $FAILED"

          echo "Flaky : $FLAKY"

          echo "Total : $TOTAL"

        # ===============================
      # Restore Allure History
      # ===============================
      - name: Restore Allure History
        if: always()
        run: |
          git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages || true

          if [ -d gh-pages/history ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/history/* allure-results/history/
          fi

      # ===============================
      # Environment Information
      # ===============================
      - name: Create environment.properties
        if: always()
        run: |
          mkdir -p allure-results

          echo "Environment=DEV" > allure-results/environment.properties
          echo "Browser=Chromium" >> allure-results/environment.properties
          echo "OS=Ubuntu Latest" >> allure-results/environment.properties
          echo "Node=$(node -v)" >> allure-results/environment.properties
          echo "Playwright=$(npx playwright --version)" >> allure-results/environment.properties
          echo "Base URL=https://dev.intelehealth.org" >> allure-results/environment.properties

      # ===============================
      # Executor Information
      # ===============================
      - name: Create executor.json
        if: always()
        run: |
          cat > allure-results/executor.json <<EOF
          {
            "name":"GitHub Actions",
            "type":"github",
            "url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "buildOrder":"${{ github.run_number }}",
            "buildName":"Run #${{ github.run_number }}",
            "buildUrl":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "reportUrl":"https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
          }
          EOF

      # ===============================
      # Install Allure
      # ===============================
      - name: Install Allure
        if: always()
        run: npm install -g allure-commandline

      # ===============================
      # Generate Report
      # ===============================
      - name: Generate Allure Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report

      # ===============================
      # Preserve History
      # ===============================
      - name: Preserve History
        if: always()
        run: |
          mkdir -p allure-report/history

          if [ -d allure-results/history ]; then
            cp -r allure-results/history/* allure-report/history/
          fi

      # ===============================
      # Upload Allure Results
      # ===============================
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      # ===============================
      # Upload Allure Report
      # ===============================
      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # ===============================
      # Deploy GitHub Pages
      # ===============================
      - name: Deploy Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report

      # ===============================
      # Report URL
      # ===============================
      - name: Print Report URL
        run: |
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
      
                # ===============================
      # Slack Final Notification
      # ===============================
      - name: Slack Final Notification
        if: always()
        run: |
          IST_TIME=$(TZ='Asia/Kolkata' date '+%Y-%m-%d %H:%M:%S IST')

          STATUS="✅ PASSED"

          if [ "${{ steps.results.outputs.failed }}" != "0" ]; then
            STATUS="❌ FAILED"
          elif [ "${{ steps.results.outputs.flaky }}" != "0" ]; then
            STATUS="⚠️ PASSED WITH FLAKY TESTS"
          fi

          REPORT_URL="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"

          curl -X POST \
          -H "Content-Type: application/json" \
          --data "{
            \"blocks\": [

              {
                \"type\": \"header\",
                \"text\": {
                  \"type\": \"plain_text\",
                  \"text\": \"${STATUS}\"
                }
              },

              {
                \"type\": \"divider\"
              },

              {
                \"type\": \"section\",
                \"fields\": [

                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*📦 Repository:*\n${{ github.repository }}\"
                  },

                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*🌿 Branch:*\n${{ github.ref_name }}\"
                  },

                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*👤 Triggered By:*\n${{ github.actor }}\"
                  },

                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*🔢 Run Number:*\n#${{ github.run_number }}\"
                  }

                ]
              },

              {
                \"type\": \"divider\"
              },

              {
                \"type\": \"section\",
                \"fields\": [

                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*✅ Passed*\n${{ steps.results.outputs.passed }}\"
                  },

                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*❌ Failed*\n${{ steps.results.outputs.failed }}\"
                  },

                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*⚠️ Flaky*\n${{ steps.results.outputs.flaky }}\"
                  },

                  {
                    \"type\": \"mrkdwn\",
                    \"text\": \"*📊 Total*\n${{ steps.results.outputs.total }}\"
                  }

                ]
              },

              {
                \"type\": \"divider\"
              },

              {
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \"*📝 Commit:*\nhttps://github.com/${{ github.repository }}/commit/${{ github.sha }}\"
                }
              },

              {
                \"type\": \"section\",
                \"text\": {
                  \"type\": \"mrkdwn\",
                  \"text\": \"*🕒 Execution Time:*\n${IST_TIME}\"
                }
              },

              {
                \"type\": \"actions\",
                \"elements\": [

                  {
                    \"type\": \"button\",
                    \"style\": \"primary\",
                    \"text\": {
                      \"type\": \"plain_text\",
                      \"text\": \"📊 View Allure Report\"
                    },
                    \"url\": \"${REPORT_URL}\"
                  },

                  {
                    \"type\": \"button\",
                    \"text\": {
                      \"type\": \"plain_text\",
                      \"text\": \"📄 GitHub Logs\"
                    },
                    \"url\": \"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"
                  }

                ]
              }

            ]
          }" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

          echo "Slack notification sent successfully."